name: bc108
description: "Implementation of the 'Biblioteca Compartilhada' v1.08 specification."
version: 0.1.6
homepage: https://github.com/mniak/bc108

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2
  collection: ^1.14.13
  matcher: ^0.12.9
  convert: ^2.1.1
  synchronized: ^2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  faker: ^1.2.1
  rxdart: ^0.24.1

# The following section is specific to Flutter.
flutter:
  # none