name: bc108
description: "Implementation of the 'Biblioteca Compartilhada' v1.08 specification."
version: 0.1.8
homepage: https://github.com/mniak/bc108

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  async: ^2.4.2
  collection: ^1.14.13
  convert: ^2.1.1
  matcher: ^0.12.9
  synchronized: ^2.2.0+2

dev_dependencies:
  faker: ^1.2.1
  mockito: ^4.1.3
  rxdart: ^0.24.1
  test: ^1.15.7
