name: Publish Library to pub.dev

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish Library to pub.dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
      - run: dart pub get
      - run: dart test
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_CACHE_CREDENTIALS_JSON }}
          flutter_package: false
          skip_test: true
